{
    "userName":"Username",
    "password":"Password",
    "please enter your user name":"Please enter your user name!",
    "please enter your password":"Please enter your password!",
    "OK":"OK",
    "Warning":"Warning",
    "Welcome":"Welcome,",
    "Quit":"Quit",
    "StorageManagement":"Storage Management",
    "fileName":"File Name",
    "createTime":"Time",
    "fileSize":"File Size",
    "Operation":"Operation",
    "play":"Play",
    "download":"Download",
    "beforePageText": "Page",
    "firstText": "First Page",
    "prevText": "Previous Page",
    "nextText": "Next Page",
    "lastText": "Last Page",
    "refreshText": "Refresh",
    "please wait":"Please wait...",
    "errorNotice":"Notice",
    "the expiry date should be later than effective date":"the end time should be later than start time",
    "startTime":"Start Time",
    "endTime":"End Time",
    "module":"Module",
    "copy":"Copy",
    "Please Select":"Please Select",
    "downloadPlay":"Download the player",
    "ip":"IP",
     "username":"Username",
    "operationTime":"Operation Time",
    "operationType":"Operation Type",
    "login":"Login",
    "find":"Find",
    "operationLog":"Operation Log"
}