{
    "userName":"用户名",
    "password":"密  码",
    "please enter your user name":"请输入用户名！",
    "please enter your password":"请输入密码！",
    "OK":"确认",
    "Warning":"警告",
    "Welcome":"欢迎，",
    "Quit":"退出",
    "StorageManagement":"存储管理",
    "fileName":"文件名称",
    "createTime":"时间",
    "fileSize":"文件大小",
    "Operation":"操作",
    "play":"播放",
    "download":"下载",
    "beforePageText": "第",
    "firstText": "第一页",
    "prevText": "上一页",
    "nextText": "下一页",
    "lastText": "最后页",
    "refreshText": "刷新",
    "please wait":"请稍候...",
    "errorNotice":"提示",
    "the expiry date should be later than effective date":"结束日期不能小于起始日期！",
    "startTime":"起始日期",
    "endTime":"结束日期",
    "module":"模块",
    "copy":"复制",
    "Please Select":"请选择",
    "downloadPlay":"下载播放器",
    "ip":"IP地址",
    "username":"用户名",
    "operationTime":"操作时间",
    "operationType":"操作类型",
    "login":"登录",
    "find":"查询",
    "operationLog":"操作日志"
}